### ISSUE TITLE
Please check if the library belongs to Google.

### ISSUE THREAD

**Issue by 15922660642** [wuyr/GoogleLibraryVersionQuerier#14]
您好,我在使用您的插件的时候遇到一个问题,我使用的versions.gradle来管理包依赖,我在app下的gradle中使用插件没有提示,查询版本时插件提示"Please check if the library belongs to Google.",然后我在versions,gradle中添加其他依赖的时候插件功能又可以完好的使用

app下的build.gradle
![Uploading 1589509256(1).jpg…]()

versions.gradle
![1589509411(1)](https://user-images.githubusercontent.com/16870825/82004821-68754c80-9696-11ea-86b2-b10544e3cbd1.jpg)

于是我尝试了添加一个module工程,在module的app下的gradle也能完整使用插件功能,但是主工程中无法使用

**Comment by wuyr** [comment]
同学你好，目前插件只支持搜索Google官方的repo，搜索jcenter仓库的功能还在开发中，"Please check if the library belongs to Google."这个提示就是说不支持搜索Google以外的仓库。

代码提示的话，因为我在编写代码的时候没有考虑到gradle的名字，所以只限定了在build.gradle这个文件内编辑才有代码提示，下个版本我取消这个限制

**Comment by 15922660642** [comment]
了解了,坐等更新插件咯
