### ISSUE TITLE
build.gradle中只要有更改就触发查询，建议优化下作用域

### ISSUE THREAD

**Issue by lanshifu** [wuyr/GoogleLibraryVersionQuerier#20]
因为是依赖库的查找，所以感觉应该控制一下作用域，只在 dependencies 代码块中才生效比较合适

![image](https://user-images.githubusercontent.com/20284668/82139822-4a0d7d80-985d-11ea-8cc0-a68caba2795d.png)

目前在dependencies以外的区域修改，也会触发查询，这不太合理

![image](https://user-images.githubusercontent.com/20284668/82139799-0fa3e080-985d-11ea-9e61-cae6fcd8fe84.png)

作者看下能不能优化下~

**Comment by wuyr** [comment]
好的，将在下个版本加上这个限制，感谢反馈~

**Comment by iOrchid** [comment]
不另开issues了，问题类似：
启用该插件的时候，在任何的编辑代码文件中（比如普通的kt文件中），输入空格都会弹出输入提示，这个算是一个副作用。
建议该插件自动联想提示，**仅作用于gradle/kts文件内，最好能判断在dependencies的闭包内**。

**Comment by wuyr** [comment]
OK，感谢反馈
