### ISSUE TITLE
有点卡。能不能把大家最终选择的库统计一下加一个排名

### ISSUE THREAD

**Issue by SJJ-dot** [wuyr/GoogleLibraryVersionQuerier#26]

**Comment by wuyr** [comment]
同学你好，目前接口没有提供这个能力，每个库被引用多少次是获取不到的。
匹配到的数据很多，可以用包名来过滤，比如要搜okhttp，可以在前面加"squ:"，也就是写成： "squ:oktttp"，这样搜出来的结果就精准很多了
