### ISSUE TITLE
版本排序有点问题，如图

### ISSUE THREAD

**Issue by gaoyl87** [wuyr/GoogleLibraryVersionQuerier#31]
![微信截图_20200602191712](https://user-images.githubusercontent.com/9102679/83514350-10e43700-a506-11ea-9668-64c465e50ef7.png)

testImplementation 'junit:junit:4.xx'
目前最新的是4.13，但是4.2显示在4.13的下面，排序需要做下修改

**Comment by YxmCute** [comment]
![微信截图_20200611160002](https://user-images.githubusercontent.com/21116914/84360453-acf3f980-abfc-11ea-89f1-3f81a5765830.png)
我也遇到了

**Comment by wixche** [comment]
遇到排序问题+1；
butterknife 库最新版排到中间去了

**Comment by wuyr** [comment]
好的，感谢指出，周末修复

**Comment by wuyr** [comment]
同学你好，V3.2已修复此问题:  <https://github.com/wuyr/GoogleLibraryVersionQuerier/releases>

**Comment by gaoyl87** [comment]
> 同学你好，V3.2已修复此问题: https://github.com/wuyr/GoogleLibraryVersionQuerier/releases

感谢
