### ISSUE TITLE
提示中出现 %23 转义字符

### ISSUE THREAD

**Issue by IAn2018cs** [wuyr/GoogleLibraryVersionQuerier#34]
如下图所示：
当输入 squ:okhttp 的时候，提示里会有以 %23 开头的内容。
![image](https://user-images.githubusercontent.com/18318073/88608013-56128880-d0b3-11ea-975f-2d63ea528be8.png)

**Comment by wuyr** [comment]
这是这个库本身的名字。。。。应该是它们发布的时候搞错了。
