### ISSUE TITLE
引入依赖包时的提示前面会有特殊字符

### ISSUE THREAD

**Issue by linmii** [wuyr/GoogleLibraryVersionQuerier#38]
如下图所示，这是阿里云返回的数据问题吗？

![image](https://user-images.githubusercontent.com/17309471/103285684-cd10cc00-4a19-11eb-9821-2833183e0450.png)
![image](https://user-images.githubusercontent.com/17309471/103285706-d8fc8e00-4a19-11eb-9dc0-5829d9d2db38.png)

**Comment by wuyr** [comment]
噢，是的，是接口数据的问题。。。
