### ISSUE TITLE
MPAndroidChart不提示

### ISSUE THREAD

**Issue by lydlovezjr** [wuyr/GoogleLibraryVersionQuerier#40]
![360截图20210304161947769](https://user-images.githubusercontent.com/19246347/109932694-7f5c5c80-7d05-11eb-9a05-c4a06bdbbdcd.jpg)

**Comment by lydlovezjr** [comment]
com.github.lihangleo2:ShadowLayout:3.2.0,这个库也是这个提示
https://github.com/lihangleo2/ShadowLayout

**Comment by lydlovezjr** [comment]
//ShadowLayout
        implementation 'com.github.lihangleo2:ShadowLayout:3.2.0'
        //圆角
        implementation 'com.github.KuangGang:RoundCorners:1.1.0'
        //卷尺
        implementation 'com.github.superSp:RulerView:v1.5'
        //签名
        implementation 'com.github.F1ReKing:SignatureView:1.1.0'
        //图片浏览器
        implementation 'com.github.maning0303:MNImageBrowser:V1.3.7'
        //MPAndroidChart
        implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

**Comment by lydlovezjr** [comment]
这六个都是发布到jitpack上了.
所以现在的插件还不支持jitpack查询对吧,大佬

**Comment by wuyr** [comment]
是的，jitpack暂时未支持，只支持google、maven和jcenter这几个仓库

**Comment by lydlovezjr** [comment]
好的,谢谢大佬
