### ISSUE TITLE
RxHttp没有更新2.6.0,却有提示

### ISSUE THREAD

**Issue by lydlovezjr** [wuyr/GoogleLibraryVersionQuerier#41]
![360截图20210304163326874](https://user-images.githubusercontent.com/19246347/109934330-5dfc7000-7d07-11eb-9bc2-a90047a4ede0.jpg)

**Comment by lydlovezjr** [comment]
https://github.com/liujingxing/okhttp-RxHttp

**Comment by lydlovezjr** [comment]
![Uploading 微信截图_20210304163645.png…]()

**Comment by lydlovezjr** [comment]
<img width="628" alt="微信截图_20210304163645" src="https://user-images.githubusercontent.com/19246347/109934826-e418b680-7d07-11eb-8dae-5e4bcfa0c914.png">

**Comment by lydlovezjr** [comment]
![360截图20210304164228710](https://user-images.githubusercontent.com/19246347/109935529-a700f400-7d08-11eb-9032-e2536efcebdf.jpg)

**Comment by wuyr** [comment]
估计是啊里云的仓库还没更新

**Comment by wuyr** [comment]
估计是啊里云的仓库还没同步

**Comment by lydlovezjr** [comment]
好的,谢谢大佬
